name: project1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  page_transition: "^2.1.0" #스플래쉬 화면이후 페이지 나타는방법
  lottie: ^3.1.2 # 스플래쉬 애니메이션
  http: ^1.2.2 #api통신
  shared_preferences: ^2.0.6
  flutter_feather_icons: ^2.0.0 # 상단바 아이콘
  intl: ^0.19.0 #날짜
  stop_watch_timer: #타이머
  flutter_dotenv: ^5.0.2 #서버 ip보안
  google_fonts: ^6.2.1 #아이콘및 폰트
  flutter_screenutil: ^5.9.3 #해상도
  flutter_secure_storage: ^8.0.0 # 토큰
  table_calendar: ^3.1.2 #캘린더
  wakelock: ^0.6.2 # 화면잠금
  encrypt: ^5.0.0
  #flutter_animated_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/demo1.png
    - assets/images/demo2.png
    - assets/study.json
    - assets/images/logo.png
    - assets/images/hitthebook.jpg
    - assets/images/timegoal.png
    - assets/levels/
    - assets/emblem/
    - assets/images/splash.gif
    - .env