
final Map<int, String> levelImages = {
  1: 'assets/levels/BLUE_5.png',
  2: 'assets/levels/BLUE_4.png',
  3: 'assets/levels/BLUE_3.png',
  4: 'assets/levels/BLUE_2.png',
  5: 'assets/levels/BLUE_1.png',
  6: 'assets/levels/GREEN_5.png',
  7: 'assets/levels/GREEN_4.png',
  8: 'assets/levels/GREEN_3.png',
  9: 'assets/levels/GREEN_2.png',
  10: 'assets/levels/GREEN_1.png',
  11: 'assets/levels/YELLOW_5.png',
  12: 'assets/levels/YELLOW_4.png',
  13: 'assets/levels/YELLOW_3.png',
  14: 'assets/levels/YELLOW_2.png',
  15: 'assets/levels/YELLOW_1.png',
  16: 'assets/levels/ORANGE_5.png',
  17: 'assets/levels/ORANGE_4.png',
  18: 'assets/levels/ORANGE_3.png',
  19: 'assets/levels/ORANGE_2.png',
  20: 'assets/levels/ORANGE_1.png',
  21: 'assets/levels/RED_5.png',
  22: 'assets/levels/RED_4.png',
  23: 'assets/levels/RED_3.png',
  24: 'assets/levels/RED_2.png',
  25: 'assets/levels/RED_1.png',
};
